name: tests

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  fast:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      AVITO_HEADLESS: "1"   # force headless in CI

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Cache pip to speed up installs
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python deps
        shell: bash
        run: |
          python -m pip install -U pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install pytest pytest-playwright playwright python-dotenv filelock
          fi

      # Cache Playwright browsers
      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-ms-playwright-${{ hashFiles('**/requirements*.txt') }}-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-ms-playwright-

      # Install Chromium + Linux deps (required on ubuntu-latest)
      - name: Install Playwright (Chromium + deps)
        run: python -m playwright install --with-deps chromium

      # Run only tests that DO NOT need logged-in Avito session
      - name: Run tests (skip auth-marked)
        run: pytest -q -m "not auth"
